// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.myshop.domain;

import com.myshop.domain.AddressType;
import com.myshop.domain.AddressTypeDataOnDemand;
import com.myshop.domain.AddressTypeIntegrationTest;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect AddressTypeIntegrationTest_Roo_IntegrationTest {
    
    declare @type: AddressTypeIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: AddressTypeIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: AddressTypeIntegrationTest: @Transactional;
    
    @Autowired
    AddressTypeDataOnDemand AddressTypeIntegrationTest.dod;
    
    @Test
    public void AddressTypeIntegrationTest.testCountAddressTypes() {
        Assert.assertNotNull("Data on demand for 'AddressType' failed to initialize correctly", dod.getRandomAddressType());
        long count = AddressType.countAddressTypes();
        Assert.assertTrue("Counter for 'AddressType' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void AddressTypeIntegrationTest.testFindAddressType() {
        AddressType obj = dod.getRandomAddressType();
        Assert.assertNotNull("Data on demand for 'AddressType' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'AddressType' failed to provide an identifier", id);
        obj = AddressType.findAddressType(id);
        Assert.assertNotNull("Find method for 'AddressType' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'AddressType' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void AddressTypeIntegrationTest.testFindAllAddressTypes() {
        Assert.assertNotNull("Data on demand for 'AddressType' failed to initialize correctly", dod.getRandomAddressType());
        long count = AddressType.countAddressTypes();
        Assert.assertTrue("Too expensive to perform a find all test for 'AddressType', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<AddressType> result = AddressType.findAllAddressTypes();
        Assert.assertNotNull("Find all method for 'AddressType' illegally returned null", result);
        Assert.assertTrue("Find all method for 'AddressType' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void AddressTypeIntegrationTest.testFindAddressTypeEntries() {
        Assert.assertNotNull("Data on demand for 'AddressType' failed to initialize correctly", dod.getRandomAddressType());
        long count = AddressType.countAddressTypes();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<AddressType> result = AddressType.findAddressTypeEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'AddressType' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'AddressType' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void AddressTypeIntegrationTest.testFlush() {
        AddressType obj = dod.getRandomAddressType();
        Assert.assertNotNull("Data on demand for 'AddressType' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'AddressType' failed to provide an identifier", id);
        obj = AddressType.findAddressType(id);
        Assert.assertNotNull("Find method for 'AddressType' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyAddressType(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'AddressType' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void AddressTypeIntegrationTest.testMergeUpdate() {
        AddressType obj = dod.getRandomAddressType();
        Assert.assertNotNull("Data on demand for 'AddressType' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'AddressType' failed to provide an identifier", id);
        obj = AddressType.findAddressType(id);
        boolean modified =  dod.modifyAddressType(obj);
        Integer currentVersion = obj.getVersion();
        AddressType merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'AddressType' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void AddressTypeIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'AddressType' failed to initialize correctly", dod.getRandomAddressType());
        AddressType obj = dod.getNewTransientAddressType(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'AddressType' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'AddressType' identifier to be null", obj.getId());
        try {
            obj.persist();
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'AddressType' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void AddressTypeIntegrationTest.testRemove() {
        AddressType obj = dod.getRandomAddressType();
        Assert.assertNotNull("Data on demand for 'AddressType' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'AddressType' failed to provide an identifier", id);
        obj = AddressType.findAddressType(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'AddressType' with identifier '" + id + "'", AddressType.findAddressType(id));
    }
    
}
