// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.myshop.domain;

import com.myshop.domain.CustomerPayment;
import com.myshop.domain.CustomerPaymentDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.stereotype.Component;

privileged aspect CustomerPaymentDataOnDemand_Roo_DataOnDemand {
    
    declare @type: CustomerPaymentDataOnDemand: @Component;
    
    private Random CustomerPaymentDataOnDemand.rnd = new SecureRandom();
    
    private List<CustomerPayment> CustomerPaymentDataOnDemand.data;
    
    public CustomerPayment CustomerPaymentDataOnDemand.getNewTransientCustomerPayment(int index) {
        CustomerPayment obj = new CustomerPayment();
        setReceivedAmount(obj, index);
        setReceivedDate(obj, index);
        setReferenceNo(obj, index);
        return obj;
    }
    
    public void CustomerPaymentDataOnDemand.setReceivedAmount(CustomerPayment obj, int index) {
        Double receivedAmount = new Integer(index).doubleValue();
        obj.setReceivedAmount(receivedAmount);
    }
    
    public void CustomerPaymentDataOnDemand.setReceivedDate(CustomerPayment obj, int index) {
        Date receivedDate = new GregorianCalendar(Calendar.getInstance().get(Calendar.YEAR), Calendar.getInstance().get(Calendar.MONTH), Calendar.getInstance().get(Calendar.DAY_OF_MONTH), Calendar.getInstance().get(Calendar.HOUR_OF_DAY), Calendar.getInstance().get(Calendar.MINUTE), Calendar.getInstance().get(Calendar.SECOND) + new Double(Math.random() * 1000).intValue()).getTime();
        obj.setReceivedDate(receivedDate);
    }
    
    public void CustomerPaymentDataOnDemand.setReferenceNo(CustomerPayment obj, int index) {
        String referenceNo = "referenceNo_" + index;
        obj.setReferenceNo(referenceNo);
    }
    
    public CustomerPayment CustomerPaymentDataOnDemand.getSpecificCustomerPayment(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        CustomerPayment obj = data.get(index);
        Long id = obj.getId();
        return CustomerPayment.findCustomerPayment(id);
    }
    
    public CustomerPayment CustomerPaymentDataOnDemand.getRandomCustomerPayment() {
        init();
        CustomerPayment obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return CustomerPayment.findCustomerPayment(id);
    }
    
    public boolean CustomerPaymentDataOnDemand.modifyCustomerPayment(CustomerPayment obj) {
        return false;
    }
    
    public void CustomerPaymentDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = CustomerPayment.findCustomerPaymentEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'CustomerPayment' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<CustomerPayment>();
        for (int i = 0; i < 10; i++) {
            CustomerPayment obj = getNewTransientCustomerPayment(i);
            try {
                obj.persist();
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
