// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.myshop.domain;

import com.myshop.domain.CustomerCreditMemo;
import com.myshop.domain.CustomerCreditMemoDataOnDemand;
import com.myshop.domain.CustomerCreditMemoIntegrationTest;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect CustomerCreditMemoIntegrationTest_Roo_IntegrationTest {
    
    declare @type: CustomerCreditMemoIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: CustomerCreditMemoIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: CustomerCreditMemoIntegrationTest: @Transactional;
    
    @Autowired
    CustomerCreditMemoDataOnDemand CustomerCreditMemoIntegrationTest.dod;
    
    @Test
    public void CustomerCreditMemoIntegrationTest.testCountCustomerCreditMemoes() {
        Assert.assertNotNull("Data on demand for 'CustomerCreditMemo' failed to initialize correctly", dod.getRandomCustomerCreditMemo());
        long count = CustomerCreditMemo.countCustomerCreditMemoes();
        Assert.assertTrue("Counter for 'CustomerCreditMemo' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void CustomerCreditMemoIntegrationTest.testFindCustomerCreditMemo() {
        CustomerCreditMemo obj = dod.getRandomCustomerCreditMemo();
        Assert.assertNotNull("Data on demand for 'CustomerCreditMemo' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'CustomerCreditMemo' failed to provide an identifier", id);
        obj = CustomerCreditMemo.findCustomerCreditMemo(id);
        Assert.assertNotNull("Find method for 'CustomerCreditMemo' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'CustomerCreditMemo' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void CustomerCreditMemoIntegrationTest.testFindAllCustomerCreditMemoes() {
        Assert.assertNotNull("Data on demand for 'CustomerCreditMemo' failed to initialize correctly", dod.getRandomCustomerCreditMemo());
        long count = CustomerCreditMemo.countCustomerCreditMemoes();
        Assert.assertTrue("Too expensive to perform a find all test for 'CustomerCreditMemo', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<CustomerCreditMemo> result = CustomerCreditMemo.findAllCustomerCreditMemoes();
        Assert.assertNotNull("Find all method for 'CustomerCreditMemo' illegally returned null", result);
        Assert.assertTrue("Find all method for 'CustomerCreditMemo' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void CustomerCreditMemoIntegrationTest.testFindCustomerCreditMemoEntries() {
        Assert.assertNotNull("Data on demand for 'CustomerCreditMemo' failed to initialize correctly", dod.getRandomCustomerCreditMemo());
        long count = CustomerCreditMemo.countCustomerCreditMemoes();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<CustomerCreditMemo> result = CustomerCreditMemo.findCustomerCreditMemoEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'CustomerCreditMemo' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'CustomerCreditMemo' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void CustomerCreditMemoIntegrationTest.testFlush() {
        CustomerCreditMemo obj = dod.getRandomCustomerCreditMemo();
        Assert.assertNotNull("Data on demand for 'CustomerCreditMemo' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'CustomerCreditMemo' failed to provide an identifier", id);
        obj = CustomerCreditMemo.findCustomerCreditMemo(id);
        Assert.assertNotNull("Find method for 'CustomerCreditMemo' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyCustomerCreditMemo(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'CustomerCreditMemo' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void CustomerCreditMemoIntegrationTest.testMergeUpdate() {
        CustomerCreditMemo obj = dod.getRandomCustomerCreditMemo();
        Assert.assertNotNull("Data on demand for 'CustomerCreditMemo' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'CustomerCreditMemo' failed to provide an identifier", id);
        obj = CustomerCreditMemo.findCustomerCreditMemo(id);
        boolean modified =  dod.modifyCustomerCreditMemo(obj);
        Integer currentVersion = obj.getVersion();
        CustomerCreditMemo merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'CustomerCreditMemo' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void CustomerCreditMemoIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'CustomerCreditMemo' failed to initialize correctly", dod.getRandomCustomerCreditMemo());
        CustomerCreditMemo obj = dod.getNewTransientCustomerCreditMemo(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'CustomerCreditMemo' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'CustomerCreditMemo' identifier to be null", obj.getId());
        try {
            obj.persist();
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'CustomerCreditMemo' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void CustomerCreditMemoIntegrationTest.testRemove() {
        CustomerCreditMemo obj = dod.getRandomCustomerCreditMemo();
        Assert.assertNotNull("Data on demand for 'CustomerCreditMemo' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'CustomerCreditMemo' failed to provide an identifier", id);
        obj = CustomerCreditMemo.findCustomerCreditMemo(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'CustomerCreditMemo' with identifier '" + id + "'", CustomerCreditMemo.findCustomerCreditMemo(id));
    }
    
}
