// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.myshop.domain;

import com.myshop.domain.CustomerPODataOnDemand;
import com.myshop.domain.CustomerPoDetails;
import com.myshop.domain.CustomerPoDetailsDataOnDemand;
import com.myshop.domain.ProductDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect CustomerPoDetailsDataOnDemand_Roo_DataOnDemand {
    
    declare @type: CustomerPoDetailsDataOnDemand: @Component;
    
    private Random CustomerPoDetailsDataOnDemand.rnd = new SecureRandom();
    
    private List<CustomerPoDetails> CustomerPoDetailsDataOnDemand.data;
    
    @Autowired
    CustomerPODataOnDemand CustomerPoDetailsDataOnDemand.customerPODataOnDemand;
    
    @Autowired
    ProductDataOnDemand CustomerPoDetailsDataOnDemand.productDataOnDemand;
    
    public CustomerPoDetails CustomerPoDetailsDataOnDemand.getNewTransientCustomerPoDetails(int index) {
        CustomerPoDetails obj = new CustomerPoDetails();
        setConfirmedDeliveryDate(obj, index);
        setDesiredDeliveryDate(obj, index);
        setOrderStatus(obj, index);
        setQty(obj, index);
        setUnit(obj, index);
        setUnitPrice(obj, index);
        return obj;
    }
    
    public void CustomerPoDetailsDataOnDemand.setConfirmedDeliveryDate(CustomerPoDetails obj, int index) {
        Date confirmedDeliveryDate = new GregorianCalendar(Calendar.getInstance().get(Calendar.YEAR), Calendar.getInstance().get(Calendar.MONTH), Calendar.getInstance().get(Calendar.DAY_OF_MONTH), Calendar.getInstance().get(Calendar.HOUR_OF_DAY), Calendar.getInstance().get(Calendar.MINUTE), Calendar.getInstance().get(Calendar.SECOND) + new Double(Math.random() * 1000).intValue()).getTime();
        obj.setConfirmedDeliveryDate(confirmedDeliveryDate);
    }
    
    public void CustomerPoDetailsDataOnDemand.setDesiredDeliveryDate(CustomerPoDetails obj, int index) {
        Date desiredDeliveryDate = new GregorianCalendar(Calendar.getInstance().get(Calendar.YEAR), Calendar.getInstance().get(Calendar.MONTH), Calendar.getInstance().get(Calendar.DAY_OF_MONTH), Calendar.getInstance().get(Calendar.HOUR_OF_DAY), Calendar.getInstance().get(Calendar.MINUTE), Calendar.getInstance().get(Calendar.SECOND) + new Double(Math.random() * 1000).intValue()).getTime();
        obj.setDesiredDeliveryDate(desiredDeliveryDate);
    }
    
    public void CustomerPoDetailsDataOnDemand.setOrderStatus(CustomerPoDetails obj, int index) {
        String orderStatus = "orderStatus_" + index;
        obj.setOrderStatus(orderStatus);
    }
    
    public void CustomerPoDetailsDataOnDemand.setQty(CustomerPoDetails obj, int index) {
        Double qty = new Integer(index).doubleValue();
        obj.setQty(qty);
    }
    
    public void CustomerPoDetailsDataOnDemand.setUnit(CustomerPoDetails obj, int index) {
        String unit = "unit_" + index;
        obj.setUnit(unit);
    }
    
    public void CustomerPoDetailsDataOnDemand.setUnitPrice(CustomerPoDetails obj, int index) {
        Double unitPrice = new Integer(index).doubleValue();
        obj.setUnitPrice(unitPrice);
    }
    
    public CustomerPoDetails CustomerPoDetailsDataOnDemand.getSpecificCustomerPoDetails(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        CustomerPoDetails obj = data.get(index);
        Long id = obj.getId();
        return CustomerPoDetails.findCustomerPoDetails(id);
    }
    
    public CustomerPoDetails CustomerPoDetailsDataOnDemand.getRandomCustomerPoDetails() {
        init();
        CustomerPoDetails obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return CustomerPoDetails.findCustomerPoDetails(id);
    }
    
    public boolean CustomerPoDetailsDataOnDemand.modifyCustomerPoDetails(CustomerPoDetails obj) {
        return false;
    }
    
    public void CustomerPoDetailsDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = CustomerPoDetails.findCustomerPoDetailsEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'CustomerPoDetails' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<CustomerPoDetails>();
        for (int i = 0; i < 10; i++) {
            CustomerPoDetails obj = getNewTransientCustomerPoDetails(i);
            try {
                obj.persist();
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
