// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.myshop.domain;

import com.myshop.domain.CustomerInvoice;
import com.myshop.domain.CustomerInvoiceDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.stereotype.Component;

privileged aspect CustomerInvoiceDataOnDemand_Roo_DataOnDemand {
    
    declare @type: CustomerInvoiceDataOnDemand: @Component;
    
    private Random CustomerInvoiceDataOnDemand.rnd = new SecureRandom();
    
    private List<CustomerInvoice> CustomerInvoiceDataOnDemand.data;
    
    public CustomerInvoice CustomerInvoiceDataOnDemand.getNewTransientCustomerInvoice(int index) {
        CustomerInvoice obj = new CustomerInvoice();
        setDueDate(obj, index);
        setInvoiceDate(obj, index);
        setStatus(obj, index);
        return obj;
    }
    
    public void CustomerInvoiceDataOnDemand.setDueDate(CustomerInvoice obj, int index) {
        Date dueDate = new GregorianCalendar(Calendar.getInstance().get(Calendar.YEAR), Calendar.getInstance().get(Calendar.MONTH), Calendar.getInstance().get(Calendar.DAY_OF_MONTH), Calendar.getInstance().get(Calendar.HOUR_OF_DAY), Calendar.getInstance().get(Calendar.MINUTE), Calendar.getInstance().get(Calendar.SECOND) + new Double(Math.random() * 1000).intValue()).getTime();
        obj.setDueDate(dueDate);
    }
    
    public void CustomerInvoiceDataOnDemand.setInvoiceDate(CustomerInvoice obj, int index) {
        Date invoiceDate = new GregorianCalendar(Calendar.getInstance().get(Calendar.YEAR), Calendar.getInstance().get(Calendar.MONTH), Calendar.getInstance().get(Calendar.DAY_OF_MONTH), Calendar.getInstance().get(Calendar.HOUR_OF_DAY), Calendar.getInstance().get(Calendar.MINUTE), Calendar.getInstance().get(Calendar.SECOND) + new Double(Math.random() * 1000).intValue()).getTime();
        obj.setInvoiceDate(invoiceDate);
    }
    
    public void CustomerInvoiceDataOnDemand.setStatus(CustomerInvoice obj, int index) {
        String status = "status_" + index;
        obj.setStatus(status);
    }
    
    public CustomerInvoice CustomerInvoiceDataOnDemand.getSpecificCustomerInvoice(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        CustomerInvoice obj = data.get(index);
        Long id = obj.getId();
        return CustomerInvoice.findCustomerInvoice(id);
    }
    
    public CustomerInvoice CustomerInvoiceDataOnDemand.getRandomCustomerInvoice() {
        init();
        CustomerInvoice obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return CustomerInvoice.findCustomerInvoice(id);
    }
    
    public boolean CustomerInvoiceDataOnDemand.modifyCustomerInvoice(CustomerInvoice obj) {
        return false;
    }
    
    public void CustomerInvoiceDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = CustomerInvoice.findCustomerInvoiceEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'CustomerInvoice' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<CustomerInvoice>();
        for (int i = 0; i < 10; i++) {
            CustomerInvoice obj = getNewTransientCustomerInvoice(i);
            try {
                obj.persist();
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
