// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.myshop.domain;

import com.myshop.domain.CustomerInvoiceDetailsDataOnDemand;
import com.myshop.domain.CustomerPaymentDataOnDemand;
import com.myshop.domain.CustomerPaymentDetail;
import com.myshop.domain.CustomerPaymentDetailDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect CustomerPaymentDetailDataOnDemand_Roo_DataOnDemand {
    
    declare @type: CustomerPaymentDetailDataOnDemand: @Component;
    
    private Random CustomerPaymentDetailDataOnDemand.rnd = new SecureRandom();
    
    private List<CustomerPaymentDetail> CustomerPaymentDetailDataOnDemand.data;
    
    @Autowired
    CustomerInvoiceDetailsDataOnDemand CustomerPaymentDetailDataOnDemand.customerInvoiceDetailsDataOnDemand;
    
    @Autowired
    CustomerPaymentDataOnDemand CustomerPaymentDetailDataOnDemand.customerPaymentDataOnDemand;
    
    public CustomerPaymentDetail CustomerPaymentDetailDataOnDemand.getNewTransientCustomerPaymentDetail(int index) {
        CustomerPaymentDetail obj = new CustomerPaymentDetail();
        setAmount(obj, index);
        return obj;
    }
    
    public void CustomerPaymentDetailDataOnDemand.setAmount(CustomerPaymentDetail obj, int index) {
        Double amount = new Integer(index).doubleValue();
        obj.setAmount(amount);
    }
    
    public CustomerPaymentDetail CustomerPaymentDetailDataOnDemand.getSpecificCustomerPaymentDetail(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        CustomerPaymentDetail obj = data.get(index);
        Long id = obj.getId();
        return CustomerPaymentDetail.findCustomerPaymentDetail(id);
    }
    
    public CustomerPaymentDetail CustomerPaymentDetailDataOnDemand.getRandomCustomerPaymentDetail() {
        init();
        CustomerPaymentDetail obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return CustomerPaymentDetail.findCustomerPaymentDetail(id);
    }
    
    public boolean CustomerPaymentDetailDataOnDemand.modifyCustomerPaymentDetail(CustomerPaymentDetail obj) {
        return false;
    }
    
    public void CustomerPaymentDetailDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = CustomerPaymentDetail.findCustomerPaymentDetailEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'CustomerPaymentDetail' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<CustomerPaymentDetail>();
        for (int i = 0; i < 10; i++) {
            CustomerPaymentDetail obj = getNewTransientCustomerPaymentDetail(i);
            try {
                obj.persist();
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
