// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.myshop.domain;

import com.myshop.domain.Customer;
import com.myshop.domain.CustomerInvoiceDetails;
import com.myshop.domain.CustomerInvoiceDetailsDataOnDemand;
import com.myshop.domain.CustomerPoDetailsDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect CustomerInvoiceDetailsDataOnDemand_Roo_DataOnDemand {
    
    declare @type: CustomerInvoiceDetailsDataOnDemand: @Component;
    
    private Random CustomerInvoiceDetailsDataOnDemand.rnd = new SecureRandom();
    
    private List<CustomerInvoiceDetails> CustomerInvoiceDetailsDataOnDemand.data;
    
    @Autowired
    CustomerPoDetailsDataOnDemand CustomerInvoiceDetailsDataOnDemand.customerPoDetailsDataOnDemand;
    
    public CustomerInvoiceDetails CustomerInvoiceDetailsDataOnDemand.getNewTransientCustomerInvoiceDetails(int index) {
        CustomerInvoiceDetails obj = new CustomerInvoiceDetails();
        setCustomerId(obj, index);
        setInvoiceQty(obj, index);
        setStatus(obj, index);
        setUnit(obj, index);
        setUnitPrice(obj, index);
        return obj;
    }
    
    public void CustomerInvoiceDetailsDataOnDemand.setCustomerId(CustomerInvoiceDetails obj, int index) {
        Customer customerId = null;
        obj.setCustomerId(customerId);
    }
    
    public void CustomerInvoiceDetailsDataOnDemand.setInvoiceQty(CustomerInvoiceDetails obj, int index) {
        Double invoiceQty = new Integer(index).doubleValue();
        obj.setInvoiceQty(invoiceQty);
    }
    
    public void CustomerInvoiceDetailsDataOnDemand.setStatus(CustomerInvoiceDetails obj, int index) {
        String status = "status_" + index;
        obj.setStatus(status);
    }
    
    public void CustomerInvoiceDetailsDataOnDemand.setUnit(CustomerInvoiceDetails obj, int index) {
        String unit = "unit_" + index;
        obj.setUnit(unit);
    }
    
    public void CustomerInvoiceDetailsDataOnDemand.setUnitPrice(CustomerInvoiceDetails obj, int index) {
        Double unitPrice = new Integer(index).doubleValue();
        obj.setUnitPrice(unitPrice);
    }
    
    public CustomerInvoiceDetails CustomerInvoiceDetailsDataOnDemand.getSpecificCustomerInvoiceDetails(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        CustomerInvoiceDetails obj = data.get(index);
        Long id = obj.getId();
        return CustomerInvoiceDetails.findCustomerInvoiceDetails(id);
    }
    
    public CustomerInvoiceDetails CustomerInvoiceDetailsDataOnDemand.getRandomCustomerInvoiceDetails() {
        init();
        CustomerInvoiceDetails obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return CustomerInvoiceDetails.findCustomerInvoiceDetails(id);
    }
    
    public boolean CustomerInvoiceDetailsDataOnDemand.modifyCustomerInvoiceDetails(CustomerInvoiceDetails obj) {
        return false;
    }
    
    public void CustomerInvoiceDetailsDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = CustomerInvoiceDetails.findCustomerInvoiceDetailsEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'CustomerInvoiceDetails' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<CustomerInvoiceDetails>();
        for (int i = 0; i < 10; i++) {
            CustomerInvoiceDetails obj = getNewTransientCustomerInvoiceDetails(i);
            try {
                obj.persist();
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
