// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.myshop.domain;

import com.myshop.domain.PaymentSentDataOnDemand;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect PaymentSentDataOnDemand_Roo_Configurable {
    
    declare @type: PaymentSentDataOnDemand: @Configurable;
    
}
