// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.myshop.domain;

import com.myshop.domain.ProductDataOnDemand;
import com.myshop.domain.ProductsReceived;
import com.myshop.domain.ProductsReceivedDataOnDemand;
import com.myshop.domain.VendorPoDetailDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect ProductsReceivedDataOnDemand_Roo_DataOnDemand {
    
    declare @type: ProductsReceivedDataOnDemand: @Component;
    
    private Random ProductsReceivedDataOnDemand.rnd = new SecureRandom();
    
    private List<ProductsReceived> ProductsReceivedDataOnDemand.data;
    
    @Autowired
    ProductDataOnDemand ProductsReceivedDataOnDemand.productDataOnDemand;
    
    @Autowired
    VendorPoDetailDataOnDemand ProductsReceivedDataOnDemand.vendorPoDetailDataOnDemand;
    
    public ProductsReceived ProductsReceivedDataOnDemand.getNewTransientProductsReceived(int index) {
        ProductsReceived obj = new ProductsReceived();
        setReceivedDate(obj, index);
        setReceivedQty(obj, index);
        return obj;
    }
    
    public void ProductsReceivedDataOnDemand.setReceivedDate(ProductsReceived obj, int index) {
        Date receivedDate = new GregorianCalendar(Calendar.getInstance().get(Calendar.YEAR), Calendar.getInstance().get(Calendar.MONTH), Calendar.getInstance().get(Calendar.DAY_OF_MONTH), Calendar.getInstance().get(Calendar.HOUR_OF_DAY), Calendar.getInstance().get(Calendar.MINUTE), Calendar.getInstance().get(Calendar.SECOND) + new Double(Math.random() * 1000).intValue()).getTime();
        obj.setReceivedDate(receivedDate);
    }
    
    public void ProductsReceivedDataOnDemand.setReceivedQty(ProductsReceived obj, int index) {
        Double receivedQty = new Integer(index).doubleValue();
        obj.setReceivedQty(receivedQty);
    }
    
    public ProductsReceived ProductsReceivedDataOnDemand.getSpecificProductsReceived(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        ProductsReceived obj = data.get(index);
        Long id = obj.getId();
        return ProductsReceived.findProductsReceived(id);
    }
    
    public ProductsReceived ProductsReceivedDataOnDemand.getRandomProductsReceived() {
        init();
        ProductsReceived obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return ProductsReceived.findProductsReceived(id);
    }
    
    public boolean ProductsReceivedDataOnDemand.modifyProductsReceived(ProductsReceived obj) {
        return false;
    }
    
    public void ProductsReceivedDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = ProductsReceived.findProductsReceivedEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'ProductsReceived' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<ProductsReceived>();
        for (int i = 0; i < 10; i++) {
            ProductsReceived obj = getNewTransientProductsReceived(i);
            try {
                obj.persist();
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
