// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.myshop.domain;

import com.myshop.domain.ProductInventory;
import com.myshop.domain.ProductInventoryDataOnDemand;
import com.myshop.domain.ProductInventoryIntegrationTest;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect ProductInventoryIntegrationTest_Roo_IntegrationTest {
    
    declare @type: ProductInventoryIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: ProductInventoryIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: ProductInventoryIntegrationTest: @Transactional;
    
    @Autowired
    ProductInventoryDataOnDemand ProductInventoryIntegrationTest.dod;
    
    @Test
    public void ProductInventoryIntegrationTest.testCountProductInventorys() {
        Assert.assertNotNull("Data on demand for 'ProductInventory' failed to initialize correctly", dod.getRandomProductInventory());
        long count = ProductInventory.countProductInventorys();
        Assert.assertTrue("Counter for 'ProductInventory' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void ProductInventoryIntegrationTest.testFindProductInventory() {
        ProductInventory obj = dod.getRandomProductInventory();
        Assert.assertNotNull("Data on demand for 'ProductInventory' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'ProductInventory' failed to provide an identifier", id);
        obj = ProductInventory.findProductInventory(id);
        Assert.assertNotNull("Find method for 'ProductInventory' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'ProductInventory' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void ProductInventoryIntegrationTest.testFindAllProductInventorys() {
        Assert.assertNotNull("Data on demand for 'ProductInventory' failed to initialize correctly", dod.getRandomProductInventory());
        long count = ProductInventory.countProductInventorys();
        Assert.assertTrue("Too expensive to perform a find all test for 'ProductInventory', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<ProductInventory> result = ProductInventory.findAllProductInventorys();
        Assert.assertNotNull("Find all method for 'ProductInventory' illegally returned null", result);
        Assert.assertTrue("Find all method for 'ProductInventory' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void ProductInventoryIntegrationTest.testFindProductInventoryEntries() {
        Assert.assertNotNull("Data on demand for 'ProductInventory' failed to initialize correctly", dod.getRandomProductInventory());
        long count = ProductInventory.countProductInventorys();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<ProductInventory> result = ProductInventory.findProductInventoryEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'ProductInventory' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'ProductInventory' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void ProductInventoryIntegrationTest.testFlush() {
        ProductInventory obj = dod.getRandomProductInventory();
        Assert.assertNotNull("Data on demand for 'ProductInventory' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'ProductInventory' failed to provide an identifier", id);
        obj = ProductInventory.findProductInventory(id);
        Assert.assertNotNull("Find method for 'ProductInventory' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyProductInventory(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'ProductInventory' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void ProductInventoryIntegrationTest.testMergeUpdate() {
        ProductInventory obj = dod.getRandomProductInventory();
        Assert.assertNotNull("Data on demand for 'ProductInventory' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'ProductInventory' failed to provide an identifier", id);
        obj = ProductInventory.findProductInventory(id);
        boolean modified =  dod.modifyProductInventory(obj);
        Integer currentVersion = obj.getVersion();
        ProductInventory merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'ProductInventory' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void ProductInventoryIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'ProductInventory' failed to initialize correctly", dod.getRandomProductInventory());
        ProductInventory obj = dod.getNewTransientProductInventory(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'ProductInventory' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'ProductInventory' identifier to be null", obj.getId());
        try {
            obj.persist();
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'ProductInventory' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void ProductInventoryIntegrationTest.testRemove() {
        ProductInventory obj = dod.getRandomProductInventory();
        Assert.assertNotNull("Data on demand for 'ProductInventory' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'ProductInventory' failed to provide an identifier", id);
        obj = ProductInventory.findProductInventory(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'ProductInventory' with identifier '" + id + "'", ProductInventory.findProductInventory(id));
    }
    
}
