// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.myshop.domain;

import com.myshop.domain.CompanyShippingAddressDataOnDemand;
import com.myshop.domain.ProductDataOnDemand;
import com.myshop.domain.ProductInventory;
import com.myshop.domain.ProductInventoryDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect ProductInventoryDataOnDemand_Roo_DataOnDemand {
    
    declare @type: ProductInventoryDataOnDemand: @Component;
    
    private Random ProductInventoryDataOnDemand.rnd = new SecureRandom();
    
    private List<ProductInventory> ProductInventoryDataOnDemand.data;
    
    @Autowired
    ProductDataOnDemand ProductInventoryDataOnDemand.productDataOnDemand;
    
    @Autowired
    CompanyShippingAddressDataOnDemand ProductInventoryDataOnDemand.companyShippingAddressDataOnDemand;
    
    public ProductInventory ProductInventoryDataOnDemand.getNewTransientProductInventory(int index) {
        ProductInventory obj = new ProductInventory();
        setInventoryQty(obj, index);
        setRoomNo(obj, index);
        setSeatNo(obj, index);
        setShelfNo(obj, index);
        return obj;
    }
    
    public void ProductInventoryDataOnDemand.setInventoryQty(ProductInventory obj, int index) {
        Double inventoryQty = new Integer(index).doubleValue();
        obj.setInventoryQty(inventoryQty);
    }
    
    public void ProductInventoryDataOnDemand.setRoomNo(ProductInventory obj, int index) {
        Double roomNo = new Integer(index).doubleValue();
        obj.setRoomNo(roomNo);
    }
    
    public void ProductInventoryDataOnDemand.setSeatNo(ProductInventory obj, int index) {
        Double seatNo = new Integer(index).doubleValue();
        obj.setSeatNo(seatNo);
    }
    
    public void ProductInventoryDataOnDemand.setShelfNo(ProductInventory obj, int index) {
        Double shelfNo = new Integer(index).doubleValue();
        obj.setShelfNo(shelfNo);
    }
    
    public ProductInventory ProductInventoryDataOnDemand.getSpecificProductInventory(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        ProductInventory obj = data.get(index);
        Long id = obj.getId();
        return ProductInventory.findProductInventory(id);
    }
    
    public ProductInventory ProductInventoryDataOnDemand.getRandomProductInventory() {
        init();
        ProductInventory obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return ProductInventory.findProductInventory(id);
    }
    
    public boolean ProductInventoryDataOnDemand.modifyProductInventory(ProductInventory obj) {
        return false;
    }
    
    public void ProductInventoryDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = ProductInventory.findProductInventoryEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'ProductInventory' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<ProductInventory>();
        for (int i = 0; i < 10; i++) {
            ProductInventory obj = getNewTransientProductInventory(i);
            try {
                obj.persist();
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
