// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.myshop.domain;

import com.myshop.domain.SalesChannel;
import com.myshop.domain.SalesChannelDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.stereotype.Component;

privileged aspect SalesChannelDataOnDemand_Roo_DataOnDemand {
    
    declare @type: SalesChannelDataOnDemand: @Component;
    
    private Random SalesChannelDataOnDemand.rnd = new SecureRandom();
    
    private List<SalesChannel> SalesChannelDataOnDemand.data;
    
    public SalesChannel SalesChannelDataOnDemand.getNewTransientSalesChannel(int index) {
        SalesChannel obj = new SalesChannel();
        setNote(obj, index);
        setSalesChannelCommission(obj, index);
        setSalesChannelName(obj, index);
        return obj;
    }
    
    public void SalesChannelDataOnDemand.setNote(SalesChannel obj, int index) {
        String note = "note_" + index;
        obj.setNote(note);
    }
    
    public void SalesChannelDataOnDemand.setSalesChannelCommission(SalesChannel obj, int index) {
        Double salesChannelCommission = new Integer(index).doubleValue();
        obj.setSalesChannelCommission(salesChannelCommission);
    }
    
    public void SalesChannelDataOnDemand.setSalesChannelName(SalesChannel obj, int index) {
        String salesChannelName = "salesChannelName_" + index;
        obj.setSalesChannelName(salesChannelName);
    }
    
    public SalesChannel SalesChannelDataOnDemand.getSpecificSalesChannel(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        SalesChannel obj = data.get(index);
        Long id = obj.getId();
        return SalesChannel.findSalesChannel(id);
    }
    
    public SalesChannel SalesChannelDataOnDemand.getRandomSalesChannel() {
        init();
        SalesChannel obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return SalesChannel.findSalesChannel(id);
    }
    
    public boolean SalesChannelDataOnDemand.modifySalesChannel(SalesChannel obj) {
        return false;
    }
    
    public void SalesChannelDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = SalesChannel.findSalesChannelEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'SalesChannel' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<SalesChannel>();
        for (int i = 0; i < 10; i++) {
            SalesChannel obj = getNewTransientSalesChannel(i);
            try {
                obj.persist();
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
