// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.myshop.domain;

import com.myshop.domain.SalesChannel;
import com.myshop.domain.SalesChannelDataOnDemand;
import com.myshop.domain.SalesChannelIntegrationTest;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect SalesChannelIntegrationTest_Roo_IntegrationTest {
    
    declare @type: SalesChannelIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: SalesChannelIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: SalesChannelIntegrationTest: @Transactional;
    
    @Autowired
    SalesChannelDataOnDemand SalesChannelIntegrationTest.dod;
    
    @Test
    public void SalesChannelIntegrationTest.testCountSalesChannels() {
        Assert.assertNotNull("Data on demand for 'SalesChannel' failed to initialize correctly", dod.getRandomSalesChannel());
        long count = SalesChannel.countSalesChannels();
        Assert.assertTrue("Counter for 'SalesChannel' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void SalesChannelIntegrationTest.testFindSalesChannel() {
        SalesChannel obj = dod.getRandomSalesChannel();
        Assert.assertNotNull("Data on demand for 'SalesChannel' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'SalesChannel' failed to provide an identifier", id);
        obj = SalesChannel.findSalesChannel(id);
        Assert.assertNotNull("Find method for 'SalesChannel' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'SalesChannel' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void SalesChannelIntegrationTest.testFindAllSalesChannels() {
        Assert.assertNotNull("Data on demand for 'SalesChannel' failed to initialize correctly", dod.getRandomSalesChannel());
        long count = SalesChannel.countSalesChannels();
        Assert.assertTrue("Too expensive to perform a find all test for 'SalesChannel', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<SalesChannel> result = SalesChannel.findAllSalesChannels();
        Assert.assertNotNull("Find all method for 'SalesChannel' illegally returned null", result);
        Assert.assertTrue("Find all method for 'SalesChannel' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void SalesChannelIntegrationTest.testFindSalesChannelEntries() {
        Assert.assertNotNull("Data on demand for 'SalesChannel' failed to initialize correctly", dod.getRandomSalesChannel());
        long count = SalesChannel.countSalesChannels();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<SalesChannel> result = SalesChannel.findSalesChannelEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'SalesChannel' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'SalesChannel' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void SalesChannelIntegrationTest.testFlush() {
        SalesChannel obj = dod.getRandomSalesChannel();
        Assert.assertNotNull("Data on demand for 'SalesChannel' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'SalesChannel' failed to provide an identifier", id);
        obj = SalesChannel.findSalesChannel(id);
        Assert.assertNotNull("Find method for 'SalesChannel' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifySalesChannel(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'SalesChannel' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void SalesChannelIntegrationTest.testMergeUpdate() {
        SalesChannel obj = dod.getRandomSalesChannel();
        Assert.assertNotNull("Data on demand for 'SalesChannel' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'SalesChannel' failed to provide an identifier", id);
        obj = SalesChannel.findSalesChannel(id);
        boolean modified =  dod.modifySalesChannel(obj);
        Integer currentVersion = obj.getVersion();
        SalesChannel merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'SalesChannel' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void SalesChannelIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'SalesChannel' failed to initialize correctly", dod.getRandomSalesChannel());
        SalesChannel obj = dod.getNewTransientSalesChannel(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'SalesChannel' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'SalesChannel' identifier to be null", obj.getId());
        try {
            obj.persist();
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'SalesChannel' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void SalesChannelIntegrationTest.testRemove() {
        SalesChannel obj = dod.getRandomSalesChannel();
        Assert.assertNotNull("Data on demand for 'SalesChannel' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'SalesChannel' failed to provide an identifier", id);
        obj = SalesChannel.findSalesChannel(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'SalesChannel' with identifier '" + id + "'", SalesChannel.findSalesChannel(id));
    }
    
}
