// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.myshop.domain;

import com.myshop.domain.Shipment;
import com.myshop.domain.ShipmentDataOnDemand;
import com.myshop.domain.ShipmentIntegrationTest;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect ShipmentIntegrationTest_Roo_IntegrationTest {
    
    declare @type: ShipmentIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: ShipmentIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: ShipmentIntegrationTest: @Transactional;
    
    @Autowired
    ShipmentDataOnDemand ShipmentIntegrationTest.dod;
    
    @Test
    public void ShipmentIntegrationTest.testCountShipments() {
        Assert.assertNotNull("Data on demand for 'Shipment' failed to initialize correctly", dod.getRandomShipment());
        long count = Shipment.countShipments();
        Assert.assertTrue("Counter for 'Shipment' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void ShipmentIntegrationTest.testFindShipment() {
        Shipment obj = dod.getRandomShipment();
        Assert.assertNotNull("Data on demand for 'Shipment' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Shipment' failed to provide an identifier", id);
        obj = Shipment.findShipment(id);
        Assert.assertNotNull("Find method for 'Shipment' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Shipment' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void ShipmentIntegrationTest.testFindAllShipments() {
        Assert.assertNotNull("Data on demand for 'Shipment' failed to initialize correctly", dod.getRandomShipment());
        long count = Shipment.countShipments();
        Assert.assertTrue("Too expensive to perform a find all test for 'Shipment', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Shipment> result = Shipment.findAllShipments();
        Assert.assertNotNull("Find all method for 'Shipment' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Shipment' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void ShipmentIntegrationTest.testFindShipmentEntries() {
        Assert.assertNotNull("Data on demand for 'Shipment' failed to initialize correctly", dod.getRandomShipment());
        long count = Shipment.countShipments();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Shipment> result = Shipment.findShipmentEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Shipment' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Shipment' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void ShipmentIntegrationTest.testFlush() {
        Shipment obj = dod.getRandomShipment();
        Assert.assertNotNull("Data on demand for 'Shipment' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Shipment' failed to provide an identifier", id);
        obj = Shipment.findShipment(id);
        Assert.assertNotNull("Find method for 'Shipment' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyShipment(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'Shipment' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void ShipmentIntegrationTest.testMergeUpdate() {
        Shipment obj = dod.getRandomShipment();
        Assert.assertNotNull("Data on demand for 'Shipment' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Shipment' failed to provide an identifier", id);
        obj = Shipment.findShipment(id);
        boolean modified =  dod.modifyShipment(obj);
        Integer currentVersion = obj.getVersion();
        Shipment merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'Shipment' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void ShipmentIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'Shipment' failed to initialize correctly", dod.getRandomShipment());
        Shipment obj = dod.getNewTransientShipment(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Shipment' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Shipment' identifier to be null", obj.getId());
        try {
            obj.persist();
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'Shipment' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void ShipmentIntegrationTest.testRemove() {
        Shipment obj = dod.getRandomShipment();
        Assert.assertNotNull("Data on demand for 'Shipment' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Shipment' failed to provide an identifier", id);
        obj = Shipment.findShipment(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'Shipment' with identifier '" + id + "'", Shipment.findShipment(id));
    }
    
}
