// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.myshop.domain;

import com.myshop.domain.Users;
import com.myshop.domain.UsersDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.stereotype.Component;

privileged aspect UsersDataOnDemand_Roo_DataOnDemand {
    
    declare @type: UsersDataOnDemand: @Component;
    
    private Random UsersDataOnDemand.rnd = new SecureRandom();
    
    private List<Users> UsersDataOnDemand.data;
    
    public Users UsersDataOnDemand.getNewTransientUsers(int index) {
        Users obj = new Users();
        setDob(obj, index);
        setEmailAddress(obj, index);
        setEnable(obj, index);
        setFirstName(obj, index);
        setIsOwner(obj, index);
        setJobTitle(obj, index);
        setLastName(obj, index);
        setMobile(obj, index);
        setNote(obj, index);
        setPassword(obj, index);
        setPhone(obj, index);
        return obj;
    }
    
    public void UsersDataOnDemand.setDob(Users obj, int index) {
        Date dob = new GregorianCalendar(Calendar.getInstance().get(Calendar.YEAR), Calendar.getInstance().get(Calendar.MONTH), Calendar.getInstance().get(Calendar.DAY_OF_MONTH), Calendar.getInstance().get(Calendar.HOUR_OF_DAY), Calendar.getInstance().get(Calendar.MINUTE), Calendar.getInstance().get(Calendar.SECOND) + new Double(Math.random() * 1000).intValue()).getTime();
        obj.setDob(dob);
    }
    
    public void UsersDataOnDemand.setEmailAddress(Users obj, int index) {
        String emailAddress = "foo" + index + "@bar.com";
        obj.setEmailAddress(emailAddress);
    }
    
    public void UsersDataOnDemand.setEnable(Users obj, int index) {
        Boolean enable = Boolean.TRUE;
        obj.setEnable(enable);
    }
    
    public void UsersDataOnDemand.setFirstName(Users obj, int index) {
        String firstName = "firstName_" + index;
        obj.setFirstName(firstName);
    }
    
    public void UsersDataOnDemand.setIsOwner(Users obj, int index) {
        Boolean isOwner = Boolean.TRUE;
        obj.setIsOwner(isOwner);
    }
    
    public void UsersDataOnDemand.setJobTitle(Users obj, int index) {
        String jobTitle = "jobTitle_" + index;
        obj.setJobTitle(jobTitle);
    }
    
    public void UsersDataOnDemand.setLastName(Users obj, int index) {
        String lastName = "lastName_" + index;
        obj.setLastName(lastName);
    }
    
    public void UsersDataOnDemand.setMobile(Users obj, int index) {
        String mobile = "mobilexx_" + index;
        obj.setMobile(mobile);
    }
    
    public void UsersDataOnDemand.setNote(Users obj, int index) {
        String note = "note_" + index;
        obj.setNote(note);
    }
    
    public void UsersDataOnDemand.setPassword(Users obj, int index) {
        String password = "password_" + index;
        obj.setPassword(password);
    }
    
    public void UsersDataOnDemand.setPhone(Users obj, int index) {
        String phone = "phonexxx_" + index;
        obj.setPhone(phone);
    }
    
    public Users UsersDataOnDemand.getSpecificUsers(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        Users obj = data.get(index);
        Long id = obj.getId();
        return Users.findUsers(id);
    }
    
    public Users UsersDataOnDemand.getRandomUsers() {
        init();
        Users obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return Users.findUsers(id);
    }
    
    public boolean UsersDataOnDemand.modifyUsers(Users obj) {
        return false;
    }
    
    public void UsersDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = Users.findUsersEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'Users' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<Users>();
        for (int i = 0; i < 10; i++) {
            Users obj = getNewTransientUsers(i);
            try {
                obj.persist();
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
