// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.myshop.domain;

import com.myshop.domain.AddressDataOnDemand;
import com.myshop.domain.VendorAddress;
import com.myshop.domain.VendorAddressDataOnDemand;
import com.myshop.domain.VendorDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect VendorAddressDataOnDemand_Roo_DataOnDemand {
    
    declare @type: VendorAddressDataOnDemand: @Component;
    
    private Random VendorAddressDataOnDemand.rnd = new SecureRandom();
    
    private List<VendorAddress> VendorAddressDataOnDemand.data;
    
    @Autowired
    AddressDataOnDemand VendorAddressDataOnDemand.addressDataOnDemand;
    
    @Autowired
    VendorDataOnDemand VendorAddressDataOnDemand.vendorDataOnDemand;
    
    public VendorAddress VendorAddressDataOnDemand.getNewTransientVendorAddress(int index) {
        VendorAddress obj = new VendorAddress();
        return obj;
    }
    
    public VendorAddress VendorAddressDataOnDemand.getSpecificVendorAddress(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        VendorAddress obj = data.get(index);
        Long id = obj.getId();
        return VendorAddress.findVendorAddress(id);
    }
    
    public VendorAddress VendorAddressDataOnDemand.getRandomVendorAddress() {
        init();
        VendorAddress obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return VendorAddress.findVendorAddress(id);
    }
    
    public boolean VendorAddressDataOnDemand.modifyVendorAddress(VendorAddress obj) {
        return false;
    }
    
    public void VendorAddressDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = VendorAddress.findVendorAddressEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'VendorAddress' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<VendorAddress>();
        for (int i = 0; i < 10; i++) {
            VendorAddress obj = getNewTransientVendorAddress(i);
            try {
                obj.persist();
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
