// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.myshop.domain;

import com.myshop.domain.VendorDebitMemo;
import com.myshop.domain.VendorDebitMemoDataOnDemand;
import com.myshop.domain.VendorPoDetailDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect VendorDebitMemoDataOnDemand_Roo_DataOnDemand {
    
    declare @type: VendorDebitMemoDataOnDemand: @Component;
    
    private Random VendorDebitMemoDataOnDemand.rnd = new SecureRandom();
    
    private List<VendorDebitMemo> VendorDebitMemoDataOnDemand.data;
    
    @Autowired
    VendorPoDetailDataOnDemand VendorDebitMemoDataOnDemand.vendorPoDetailDataOnDemand;
    
    public VendorDebitMemo VendorDebitMemoDataOnDemand.getNewTransientVendorDebitMemo(int index) {
        VendorDebitMemo obj = new VendorDebitMemo();
        setIsOpen(obj, index);
        setIssueDate(obj, index);
        setRejectedQty(obj, index);
        setRejectedUnitPrice(obj, index);
        return obj;
    }
    
    public void VendorDebitMemoDataOnDemand.setIsOpen(VendorDebitMemo obj, int index) {
        Boolean isOpen = Boolean.TRUE;
        obj.setIsOpen(isOpen);
    }
    
    public void VendorDebitMemoDataOnDemand.setIssueDate(VendorDebitMemo obj, int index) {
        Date issueDate = new GregorianCalendar(Calendar.getInstance().get(Calendar.YEAR), Calendar.getInstance().get(Calendar.MONTH), Calendar.getInstance().get(Calendar.DAY_OF_MONTH), Calendar.getInstance().get(Calendar.HOUR_OF_DAY), Calendar.getInstance().get(Calendar.MINUTE), Calendar.getInstance().get(Calendar.SECOND) + new Double(Math.random() * 1000).intValue()).getTime();
        obj.setIssueDate(issueDate);
    }
    
    public void VendorDebitMemoDataOnDemand.setRejectedQty(VendorDebitMemo obj, int index) {
        Double rejectedQty = new Integer(index).doubleValue();
        obj.setRejectedQty(rejectedQty);
    }
    
    public void VendorDebitMemoDataOnDemand.setRejectedUnitPrice(VendorDebitMemo obj, int index) {
        Double rejectedUnitPrice = new Integer(index).doubleValue();
        obj.setRejectedUnitPrice(rejectedUnitPrice);
    }
    
    public VendorDebitMemo VendorDebitMemoDataOnDemand.getSpecificVendorDebitMemo(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        VendorDebitMemo obj = data.get(index);
        Long id = obj.getId();
        return VendorDebitMemo.findVendorDebitMemo(id);
    }
    
    public VendorDebitMemo VendorDebitMemoDataOnDemand.getRandomVendorDebitMemo() {
        init();
        VendorDebitMemo obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return VendorDebitMemo.findVendorDebitMemo(id);
    }
    
    public boolean VendorDebitMemoDataOnDemand.modifyVendorDebitMemo(VendorDebitMemo obj) {
        return false;
    }
    
    public void VendorDebitMemoDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = VendorDebitMemo.findVendorDebitMemoEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'VendorDebitMemo' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<VendorDebitMemo>();
        for (int i = 0; i < 10; i++) {
            VendorDebitMemo obj = getNewTransientVendorDebitMemo(i);
            try {
                obj.persist();
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
