// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.myshop.domain;

import com.myshop.domain.VendorPurchaseOrder;
import com.myshop.domain.VendorPurchaseOrderDataOnDemand;
import com.myshop.domain.VendorPurchaseOrderIntegrationTest;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect VendorPurchaseOrderIntegrationTest_Roo_IntegrationTest {
    
    declare @type: VendorPurchaseOrderIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: VendorPurchaseOrderIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: VendorPurchaseOrderIntegrationTest: @Transactional;
    
    @Autowired
    VendorPurchaseOrderDataOnDemand VendorPurchaseOrderIntegrationTest.dod;
    
    @Test
    public void VendorPurchaseOrderIntegrationTest.testCountVendorPurchaseOrders() {
        Assert.assertNotNull("Data on demand for 'VendorPurchaseOrder' failed to initialize correctly", dod.getRandomVendorPurchaseOrder());
        long count = VendorPurchaseOrder.countVendorPurchaseOrders();
        Assert.assertTrue("Counter for 'VendorPurchaseOrder' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void VendorPurchaseOrderIntegrationTest.testFindVendorPurchaseOrder() {
        VendorPurchaseOrder obj = dod.getRandomVendorPurchaseOrder();
        Assert.assertNotNull("Data on demand for 'VendorPurchaseOrder' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'VendorPurchaseOrder' failed to provide an identifier", id);
        obj = VendorPurchaseOrder.findVendorPurchaseOrder(id);
        Assert.assertNotNull("Find method for 'VendorPurchaseOrder' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'VendorPurchaseOrder' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void VendorPurchaseOrderIntegrationTest.testFindAllVendorPurchaseOrders() {
        Assert.assertNotNull("Data on demand for 'VendorPurchaseOrder' failed to initialize correctly", dod.getRandomVendorPurchaseOrder());
        long count = VendorPurchaseOrder.countVendorPurchaseOrders();
        Assert.assertTrue("Too expensive to perform a find all test for 'VendorPurchaseOrder', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<VendorPurchaseOrder> result = VendorPurchaseOrder.findAllVendorPurchaseOrders();
        Assert.assertNotNull("Find all method for 'VendorPurchaseOrder' illegally returned null", result);
        Assert.assertTrue("Find all method for 'VendorPurchaseOrder' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void VendorPurchaseOrderIntegrationTest.testFindVendorPurchaseOrderEntries() {
        Assert.assertNotNull("Data on demand for 'VendorPurchaseOrder' failed to initialize correctly", dod.getRandomVendorPurchaseOrder());
        long count = VendorPurchaseOrder.countVendorPurchaseOrders();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<VendorPurchaseOrder> result = VendorPurchaseOrder.findVendorPurchaseOrderEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'VendorPurchaseOrder' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'VendorPurchaseOrder' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void VendorPurchaseOrderIntegrationTest.testFlush() {
        VendorPurchaseOrder obj = dod.getRandomVendorPurchaseOrder();
        Assert.assertNotNull("Data on demand for 'VendorPurchaseOrder' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'VendorPurchaseOrder' failed to provide an identifier", id);
        obj = VendorPurchaseOrder.findVendorPurchaseOrder(id);
        Assert.assertNotNull("Find method for 'VendorPurchaseOrder' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyVendorPurchaseOrder(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'VendorPurchaseOrder' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void VendorPurchaseOrderIntegrationTest.testMergeUpdate() {
        VendorPurchaseOrder obj = dod.getRandomVendorPurchaseOrder();
        Assert.assertNotNull("Data on demand for 'VendorPurchaseOrder' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'VendorPurchaseOrder' failed to provide an identifier", id);
        obj = VendorPurchaseOrder.findVendorPurchaseOrder(id);
        boolean modified =  dod.modifyVendorPurchaseOrder(obj);
        Integer currentVersion = obj.getVersion();
        VendorPurchaseOrder merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'VendorPurchaseOrder' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void VendorPurchaseOrderIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'VendorPurchaseOrder' failed to initialize correctly", dod.getRandomVendorPurchaseOrder());
        VendorPurchaseOrder obj = dod.getNewTransientVendorPurchaseOrder(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'VendorPurchaseOrder' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'VendorPurchaseOrder' identifier to be null", obj.getId());
        try {
            obj.persist();
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'VendorPurchaseOrder' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void VendorPurchaseOrderIntegrationTest.testRemove() {
        VendorPurchaseOrder obj = dod.getRandomVendorPurchaseOrder();
        Assert.assertNotNull("Data on demand for 'VendorPurchaseOrder' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'VendorPurchaseOrder' failed to provide an identifier", id);
        obj = VendorPurchaseOrder.findVendorPurchaseOrder(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'VendorPurchaseOrder' with identifier '" + id + "'", VendorPurchaseOrder.findVendorPurchaseOrder(id));
    }
    
}
