// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.myshop.domain;

import com.myshop.domain.VendorContactPerson;
import com.myshop.domain.VendorContactPersonDataOnDemand;
import com.myshop.domain.VendorDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect VendorContactPersonDataOnDemand_Roo_DataOnDemand {
    
    declare @type: VendorContactPersonDataOnDemand: @Component;
    
    private Random VendorContactPersonDataOnDemand.rnd = new SecureRandom();
    
    private List<VendorContactPerson> VendorContactPersonDataOnDemand.data;
    
    @Autowired
    VendorDataOnDemand VendorContactPersonDataOnDemand.vendorDataOnDemand;
    
    public VendorContactPerson VendorContactPersonDataOnDemand.getNewTransientVendorContactPerson(int index) {
        VendorContactPerson obj = new VendorContactPerson();
        setEmail(obj, index);
        setFirstName(obj, index);
        setLastName(obj, index);
        setMobile(obj, index);
        setNote(obj, index);
        setPhone(obj, index);
        setVendorPosition(obj, index);
        return obj;
    }
    
    public void VendorContactPersonDataOnDemand.setEmail(VendorContactPerson obj, int index) {
        String email = "foo" + index + "@bar.com";
        obj.setEmail(email);
    }
    
    public void VendorContactPersonDataOnDemand.setFirstName(VendorContactPerson obj, int index) {
        String firstName = "firstName_" + index;
        obj.setFirstName(firstName);
    }
    
    public void VendorContactPersonDataOnDemand.setLastName(VendorContactPerson obj, int index) {
        String lastName = "lastName_" + index;
        obj.setLastName(lastName);
    }
    
    public void VendorContactPersonDataOnDemand.setMobile(VendorContactPerson obj, int index) {
        String mobile = "mobile_" + index;
        obj.setMobile(mobile);
    }
    
    public void VendorContactPersonDataOnDemand.setNote(VendorContactPerson obj, int index) {
        String note = "note_" + index;
        obj.setNote(note);
    }
    
    public void VendorContactPersonDataOnDemand.setPhone(VendorContactPerson obj, int index) {
        String phone = "phone_" + index;
        obj.setPhone(phone);
    }
    
    public void VendorContactPersonDataOnDemand.setVendorPosition(VendorContactPerson obj, int index) {
        String vendorPosition = "vendorPosition_" + index;
        obj.setVendorPosition(vendorPosition);
    }
    
    public VendorContactPerson VendorContactPersonDataOnDemand.getSpecificVendorContactPerson(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        VendorContactPerson obj = data.get(index);
        Long id = obj.getId();
        return VendorContactPerson.findVendorContactPerson(id);
    }
    
    public VendorContactPerson VendorContactPersonDataOnDemand.getRandomVendorContactPerson() {
        init();
        VendorContactPerson obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return VendorContactPerson.findVendorContactPerson(id);
    }
    
    public boolean VendorContactPersonDataOnDemand.modifyVendorContactPerson(VendorContactPerson obj) {
        return false;
    }
    
    public void VendorContactPersonDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = VendorContactPerson.findVendorContactPersonEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'VendorContactPerson' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<VendorContactPerson>();
        for (int i = 0; i < 10; i++) {
            VendorContactPerson obj = getNewTransientVendorContactPerson(i);
            try {
                obj.persist();
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
