// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.myshop.domain;

import com.myshop.domain.VendorPaymentDetail;
import com.myshop.domain.VendorPaymentDetailDataOnDemand;
import com.myshop.domain.VendorPaymentDetailIntegrationTest;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect VendorPaymentDetailIntegrationTest_Roo_IntegrationTest {
    
    declare @type: VendorPaymentDetailIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: VendorPaymentDetailIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: VendorPaymentDetailIntegrationTest: @Transactional;
    
    @Autowired
    VendorPaymentDetailDataOnDemand VendorPaymentDetailIntegrationTest.dod;
    
    @Test
    public void VendorPaymentDetailIntegrationTest.testCountVendorPaymentDetails() {
        Assert.assertNotNull("Data on demand for 'VendorPaymentDetail' failed to initialize correctly", dod.getRandomVendorPaymentDetail());
        long count = VendorPaymentDetail.countVendorPaymentDetails();
        Assert.assertTrue("Counter for 'VendorPaymentDetail' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void VendorPaymentDetailIntegrationTest.testFindVendorPaymentDetail() {
        VendorPaymentDetail obj = dod.getRandomVendorPaymentDetail();
        Assert.assertNotNull("Data on demand for 'VendorPaymentDetail' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'VendorPaymentDetail' failed to provide an identifier", id);
        obj = VendorPaymentDetail.findVendorPaymentDetail(id);
        Assert.assertNotNull("Find method for 'VendorPaymentDetail' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'VendorPaymentDetail' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void VendorPaymentDetailIntegrationTest.testFindAllVendorPaymentDetails() {
        Assert.assertNotNull("Data on demand for 'VendorPaymentDetail' failed to initialize correctly", dod.getRandomVendorPaymentDetail());
        long count = VendorPaymentDetail.countVendorPaymentDetails();
        Assert.assertTrue("Too expensive to perform a find all test for 'VendorPaymentDetail', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<VendorPaymentDetail> result = VendorPaymentDetail.findAllVendorPaymentDetails();
        Assert.assertNotNull("Find all method for 'VendorPaymentDetail' illegally returned null", result);
        Assert.assertTrue("Find all method for 'VendorPaymentDetail' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void VendorPaymentDetailIntegrationTest.testFindVendorPaymentDetailEntries() {
        Assert.assertNotNull("Data on demand for 'VendorPaymentDetail' failed to initialize correctly", dod.getRandomVendorPaymentDetail());
        long count = VendorPaymentDetail.countVendorPaymentDetails();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<VendorPaymentDetail> result = VendorPaymentDetail.findVendorPaymentDetailEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'VendorPaymentDetail' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'VendorPaymentDetail' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void VendorPaymentDetailIntegrationTest.testFlush() {
        VendorPaymentDetail obj = dod.getRandomVendorPaymentDetail();
        Assert.assertNotNull("Data on demand for 'VendorPaymentDetail' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'VendorPaymentDetail' failed to provide an identifier", id);
        obj = VendorPaymentDetail.findVendorPaymentDetail(id);
        Assert.assertNotNull("Find method for 'VendorPaymentDetail' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyVendorPaymentDetail(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'VendorPaymentDetail' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void VendorPaymentDetailIntegrationTest.testMergeUpdate() {
        VendorPaymentDetail obj = dod.getRandomVendorPaymentDetail();
        Assert.assertNotNull("Data on demand for 'VendorPaymentDetail' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'VendorPaymentDetail' failed to provide an identifier", id);
        obj = VendorPaymentDetail.findVendorPaymentDetail(id);
        boolean modified =  dod.modifyVendorPaymentDetail(obj);
        Integer currentVersion = obj.getVersion();
        VendorPaymentDetail merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'VendorPaymentDetail' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void VendorPaymentDetailIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'VendorPaymentDetail' failed to initialize correctly", dod.getRandomVendorPaymentDetail());
        VendorPaymentDetail obj = dod.getNewTransientVendorPaymentDetail(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'VendorPaymentDetail' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'VendorPaymentDetail' identifier to be null", obj.getId());
        try {
            obj.persist();
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'VendorPaymentDetail' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void VendorPaymentDetailIntegrationTest.testRemove() {
        VendorPaymentDetail obj = dod.getRandomVendorPaymentDetail();
        Assert.assertNotNull("Data on demand for 'VendorPaymentDetail' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'VendorPaymentDetail' failed to provide an identifier", id);
        obj = VendorPaymentDetail.findVendorPaymentDetail(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'VendorPaymentDetail' with identifier '" + id + "'", VendorPaymentDetail.findVendorPaymentDetail(id));
    }
    
}
