// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.myshop.domain;

import com.myshop.domain.VendorPaymentDetailDataOnDemand;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect VendorPaymentDetailDataOnDemand_Roo_Configurable {
    
    declare @type: VendorPaymentDetailDataOnDemand: @Configurable;
    
}
