// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.myshop.domain;

import com.myshop.domain.VendorDebitMemo;
import com.myshop.domain.VendorDebitMemoDataOnDemand;
import com.myshop.domain.VendorDebitMemoIntegrationTest;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect VendorDebitMemoIntegrationTest_Roo_IntegrationTest {
    
    declare @type: VendorDebitMemoIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: VendorDebitMemoIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: VendorDebitMemoIntegrationTest: @Transactional;
    
    @Autowired
    VendorDebitMemoDataOnDemand VendorDebitMemoIntegrationTest.dod;
    
    @Test
    public void VendorDebitMemoIntegrationTest.testCountVendorDebitMemoes() {
        Assert.assertNotNull("Data on demand for 'VendorDebitMemo' failed to initialize correctly", dod.getRandomVendorDebitMemo());
        long count = VendorDebitMemo.countVendorDebitMemoes();
        Assert.assertTrue("Counter for 'VendorDebitMemo' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void VendorDebitMemoIntegrationTest.testFindVendorDebitMemo() {
        VendorDebitMemo obj = dod.getRandomVendorDebitMemo();
        Assert.assertNotNull("Data on demand for 'VendorDebitMemo' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'VendorDebitMemo' failed to provide an identifier", id);
        obj = VendorDebitMemo.findVendorDebitMemo(id);
        Assert.assertNotNull("Find method for 'VendorDebitMemo' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'VendorDebitMemo' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void VendorDebitMemoIntegrationTest.testFindAllVendorDebitMemoes() {
        Assert.assertNotNull("Data on demand for 'VendorDebitMemo' failed to initialize correctly", dod.getRandomVendorDebitMemo());
        long count = VendorDebitMemo.countVendorDebitMemoes();
        Assert.assertTrue("Too expensive to perform a find all test for 'VendorDebitMemo', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<VendorDebitMemo> result = VendorDebitMemo.findAllVendorDebitMemoes();
        Assert.assertNotNull("Find all method for 'VendorDebitMemo' illegally returned null", result);
        Assert.assertTrue("Find all method for 'VendorDebitMemo' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void VendorDebitMemoIntegrationTest.testFindVendorDebitMemoEntries() {
        Assert.assertNotNull("Data on demand for 'VendorDebitMemo' failed to initialize correctly", dod.getRandomVendorDebitMemo());
        long count = VendorDebitMemo.countVendorDebitMemoes();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<VendorDebitMemo> result = VendorDebitMemo.findVendorDebitMemoEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'VendorDebitMemo' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'VendorDebitMemo' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void VendorDebitMemoIntegrationTest.testFlush() {
        VendorDebitMemo obj = dod.getRandomVendorDebitMemo();
        Assert.assertNotNull("Data on demand for 'VendorDebitMemo' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'VendorDebitMemo' failed to provide an identifier", id);
        obj = VendorDebitMemo.findVendorDebitMemo(id);
        Assert.assertNotNull("Find method for 'VendorDebitMemo' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyVendorDebitMemo(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'VendorDebitMemo' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void VendorDebitMemoIntegrationTest.testMergeUpdate() {
        VendorDebitMemo obj = dod.getRandomVendorDebitMemo();
        Assert.assertNotNull("Data on demand for 'VendorDebitMemo' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'VendorDebitMemo' failed to provide an identifier", id);
        obj = VendorDebitMemo.findVendorDebitMemo(id);
        boolean modified =  dod.modifyVendorDebitMemo(obj);
        Integer currentVersion = obj.getVersion();
        VendorDebitMemo merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'VendorDebitMemo' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void VendorDebitMemoIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'VendorDebitMemo' failed to initialize correctly", dod.getRandomVendorDebitMemo());
        VendorDebitMemo obj = dod.getNewTransientVendorDebitMemo(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'VendorDebitMemo' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'VendorDebitMemo' identifier to be null", obj.getId());
        try {
            obj.persist();
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'VendorDebitMemo' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void VendorDebitMemoIntegrationTest.testRemove() {
        VendorDebitMemo obj = dod.getRandomVendorDebitMemo();
        Assert.assertNotNull("Data on demand for 'VendorDebitMemo' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'VendorDebitMemo' failed to provide an identifier", id);
        obj = VendorDebitMemo.findVendorDebitMemo(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'VendorDebitMemo' with identifier '" + id + "'", VendorDebitMemo.findVendorDebitMemo(id));
    }
    
}
