// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.myshop.domain;

import com.myshop.domain.VendorContactPerson;
import com.myshop.domain.VendorContactPersonDataOnDemand;
import com.myshop.domain.VendorContactPersonIntegrationTest;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect VendorContactPersonIntegrationTest_Roo_IntegrationTest {
    
    declare @type: VendorContactPersonIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: VendorContactPersonIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: VendorContactPersonIntegrationTest: @Transactional;
    
    @Autowired
    VendorContactPersonDataOnDemand VendorContactPersonIntegrationTest.dod;
    
    @Test
    public void VendorContactPersonIntegrationTest.testCountVendorContactpeople() {
        Assert.assertNotNull("Data on demand for 'VendorContactPerson' failed to initialize correctly", dod.getRandomVendorContactPerson());
        long count = VendorContactPerson.countVendorContactpeople();
        Assert.assertTrue("Counter for 'VendorContactPerson' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void VendorContactPersonIntegrationTest.testFindVendorContactPerson() {
        VendorContactPerson obj = dod.getRandomVendorContactPerson();
        Assert.assertNotNull("Data on demand for 'VendorContactPerson' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'VendorContactPerson' failed to provide an identifier", id);
        obj = VendorContactPerson.findVendorContactPerson(id);
        Assert.assertNotNull("Find method for 'VendorContactPerson' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'VendorContactPerson' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void VendorContactPersonIntegrationTest.testFindAllVendorContactpeople() {
        Assert.assertNotNull("Data on demand for 'VendorContactPerson' failed to initialize correctly", dod.getRandomVendorContactPerson());
        long count = VendorContactPerson.countVendorContactpeople();
        Assert.assertTrue("Too expensive to perform a find all test for 'VendorContactPerson', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<VendorContactPerson> result = VendorContactPerson.findAllVendorContactpeople();
        Assert.assertNotNull("Find all method for 'VendorContactPerson' illegally returned null", result);
        Assert.assertTrue("Find all method for 'VendorContactPerson' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void VendorContactPersonIntegrationTest.testFindVendorContactPersonEntries() {
        Assert.assertNotNull("Data on demand for 'VendorContactPerson' failed to initialize correctly", dod.getRandomVendorContactPerson());
        long count = VendorContactPerson.countVendorContactpeople();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<VendorContactPerson> result = VendorContactPerson.findVendorContactPersonEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'VendorContactPerson' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'VendorContactPerson' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void VendorContactPersonIntegrationTest.testFlush() {
        VendorContactPerson obj = dod.getRandomVendorContactPerson();
        Assert.assertNotNull("Data on demand for 'VendorContactPerson' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'VendorContactPerson' failed to provide an identifier", id);
        obj = VendorContactPerson.findVendorContactPerson(id);
        Assert.assertNotNull("Find method for 'VendorContactPerson' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyVendorContactPerson(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'VendorContactPerson' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void VendorContactPersonIntegrationTest.testMergeUpdate() {
        VendorContactPerson obj = dod.getRandomVendorContactPerson();
        Assert.assertNotNull("Data on demand for 'VendorContactPerson' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'VendorContactPerson' failed to provide an identifier", id);
        obj = VendorContactPerson.findVendorContactPerson(id);
        boolean modified =  dod.modifyVendorContactPerson(obj);
        Integer currentVersion = obj.getVersion();
        VendorContactPerson merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'VendorContactPerson' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void VendorContactPersonIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'VendorContactPerson' failed to initialize correctly", dod.getRandomVendorContactPerson());
        VendorContactPerson obj = dod.getNewTransientVendorContactPerson(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'VendorContactPerson' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'VendorContactPerson' identifier to be null", obj.getId());
        try {
            obj.persist();
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'VendorContactPerson' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void VendorContactPersonIntegrationTest.testRemove() {
        VendorContactPerson obj = dod.getRandomVendorContactPerson();
        Assert.assertNotNull("Data on demand for 'VendorContactPerson' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'VendorContactPerson' failed to provide an identifier", id);
        obj = VendorContactPerson.findVendorContactPerson(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'VendorContactPerson' with identifier '" + id + "'", VendorContactPerson.findVendorContactPerson(id));
    }
    
}
