// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.myshop.domain;

import com.myshop.domain.VendorPoDetail;
import com.myshop.domain.VendorPoDetailDataOnDemand;
import com.myshop.domain.VendorPoDetailIntegrationTest;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect VendorPoDetailIntegrationTest_Roo_IntegrationTest {
    
    declare @type: VendorPoDetailIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: VendorPoDetailIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: VendorPoDetailIntegrationTest: @Transactional;
    
    @Autowired
    VendorPoDetailDataOnDemand VendorPoDetailIntegrationTest.dod;
    
    @Test
    public void VendorPoDetailIntegrationTest.testCountVendorPoDetails() {
        Assert.assertNotNull("Data on demand for 'VendorPoDetail' failed to initialize correctly", dod.getRandomVendorPoDetail());
        long count = VendorPoDetail.countVendorPoDetails();
        Assert.assertTrue("Counter for 'VendorPoDetail' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void VendorPoDetailIntegrationTest.testFindVendorPoDetail() {
        VendorPoDetail obj = dod.getRandomVendorPoDetail();
        Assert.assertNotNull("Data on demand for 'VendorPoDetail' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'VendorPoDetail' failed to provide an identifier", id);
        obj = VendorPoDetail.findVendorPoDetail(id);
        Assert.assertNotNull("Find method for 'VendorPoDetail' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'VendorPoDetail' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void VendorPoDetailIntegrationTest.testFindAllVendorPoDetails() {
        Assert.assertNotNull("Data on demand for 'VendorPoDetail' failed to initialize correctly", dod.getRandomVendorPoDetail());
        long count = VendorPoDetail.countVendorPoDetails();
        Assert.assertTrue("Too expensive to perform a find all test for 'VendorPoDetail', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<VendorPoDetail> result = VendorPoDetail.findAllVendorPoDetails();
        Assert.assertNotNull("Find all method for 'VendorPoDetail' illegally returned null", result);
        Assert.assertTrue("Find all method for 'VendorPoDetail' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void VendorPoDetailIntegrationTest.testFindVendorPoDetailEntries() {
        Assert.assertNotNull("Data on demand for 'VendorPoDetail' failed to initialize correctly", dod.getRandomVendorPoDetail());
        long count = VendorPoDetail.countVendorPoDetails();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<VendorPoDetail> result = VendorPoDetail.findVendorPoDetailEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'VendorPoDetail' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'VendorPoDetail' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void VendorPoDetailIntegrationTest.testFlush() {
        VendorPoDetail obj = dod.getRandomVendorPoDetail();
        Assert.assertNotNull("Data on demand for 'VendorPoDetail' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'VendorPoDetail' failed to provide an identifier", id);
        obj = VendorPoDetail.findVendorPoDetail(id);
        Assert.assertNotNull("Find method for 'VendorPoDetail' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyVendorPoDetail(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'VendorPoDetail' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void VendorPoDetailIntegrationTest.testMergeUpdate() {
        VendorPoDetail obj = dod.getRandomVendorPoDetail();
        Assert.assertNotNull("Data on demand for 'VendorPoDetail' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'VendorPoDetail' failed to provide an identifier", id);
        obj = VendorPoDetail.findVendorPoDetail(id);
        boolean modified =  dod.modifyVendorPoDetail(obj);
        Integer currentVersion = obj.getVersion();
        VendorPoDetail merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'VendorPoDetail' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void VendorPoDetailIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'VendorPoDetail' failed to initialize correctly", dod.getRandomVendorPoDetail());
        VendorPoDetail obj = dod.getNewTransientVendorPoDetail(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'VendorPoDetail' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'VendorPoDetail' identifier to be null", obj.getId());
        try {
            obj.persist();
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'VendorPoDetail' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void VendorPoDetailIntegrationTest.testRemove() {
        VendorPoDetail obj = dod.getRandomVendorPoDetail();
        Assert.assertNotNull("Data on demand for 'VendorPoDetail' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'VendorPoDetail' failed to provide an identifier", id);
        obj = VendorPoDetail.findVendorPoDetail(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'VendorPoDetail' with identifier '" + id + "'", VendorPoDetail.findVendorPoDetail(id));
    }
    
}
