// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.myshop.domain;

import com.myshop.domain.VendorPayment;
import com.myshop.domain.VendorPaymentDataOnDemand;
import com.myshop.domain.VendorPaymentIntegrationTest;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect VendorPaymentIntegrationTest_Roo_IntegrationTest {
    
    declare @type: VendorPaymentIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: VendorPaymentIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: VendorPaymentIntegrationTest: @Transactional;
    
    @Autowired
    VendorPaymentDataOnDemand VendorPaymentIntegrationTest.dod;
    
    @Test
    public void VendorPaymentIntegrationTest.testCountVendorPayments() {
        Assert.assertNotNull("Data on demand for 'VendorPayment' failed to initialize correctly", dod.getRandomVendorPayment());
        long count = VendorPayment.countVendorPayments();
        Assert.assertTrue("Counter for 'VendorPayment' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void VendorPaymentIntegrationTest.testFindVendorPayment() {
        VendorPayment obj = dod.getRandomVendorPayment();
        Assert.assertNotNull("Data on demand for 'VendorPayment' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'VendorPayment' failed to provide an identifier", id);
        obj = VendorPayment.findVendorPayment(id);
        Assert.assertNotNull("Find method for 'VendorPayment' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'VendorPayment' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void VendorPaymentIntegrationTest.testFindAllVendorPayments() {
        Assert.assertNotNull("Data on demand for 'VendorPayment' failed to initialize correctly", dod.getRandomVendorPayment());
        long count = VendorPayment.countVendorPayments();
        Assert.assertTrue("Too expensive to perform a find all test for 'VendorPayment', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<VendorPayment> result = VendorPayment.findAllVendorPayments();
        Assert.assertNotNull("Find all method for 'VendorPayment' illegally returned null", result);
        Assert.assertTrue("Find all method for 'VendorPayment' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void VendorPaymentIntegrationTest.testFindVendorPaymentEntries() {
        Assert.assertNotNull("Data on demand for 'VendorPayment' failed to initialize correctly", dod.getRandomVendorPayment());
        long count = VendorPayment.countVendorPayments();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<VendorPayment> result = VendorPayment.findVendorPaymentEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'VendorPayment' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'VendorPayment' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void VendorPaymentIntegrationTest.testFlush() {
        VendorPayment obj = dod.getRandomVendorPayment();
        Assert.assertNotNull("Data on demand for 'VendorPayment' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'VendorPayment' failed to provide an identifier", id);
        obj = VendorPayment.findVendorPayment(id);
        Assert.assertNotNull("Find method for 'VendorPayment' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyVendorPayment(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'VendorPayment' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void VendorPaymentIntegrationTest.testMergeUpdate() {
        VendorPayment obj = dod.getRandomVendorPayment();
        Assert.assertNotNull("Data on demand for 'VendorPayment' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'VendorPayment' failed to provide an identifier", id);
        obj = VendorPayment.findVendorPayment(id);
        boolean modified =  dod.modifyVendorPayment(obj);
        Integer currentVersion = obj.getVersion();
        VendorPayment merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'VendorPayment' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void VendorPaymentIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'VendorPayment' failed to initialize correctly", dod.getRandomVendorPayment());
        VendorPayment obj = dod.getNewTransientVendorPayment(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'VendorPayment' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'VendorPayment' identifier to be null", obj.getId());
        try {
            obj.persist();
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'VendorPayment' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void VendorPaymentIntegrationTest.testRemove() {
        VendorPayment obj = dod.getRandomVendorPayment();
        Assert.assertNotNull("Data on demand for 'VendorPayment' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'VendorPayment' failed to provide an identifier", id);
        obj = VendorPayment.findVendorPayment(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'VendorPayment' with identifier '" + id + "'", VendorPayment.findVendorPayment(id));
    }
    
}
