// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.myshop.domain;

import com.myshop.domain.VendorPayment;
import com.myshop.domain.VendorPaymentDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.stereotype.Component;

privileged aspect VendorPaymentDataOnDemand_Roo_DataOnDemand {
    
    declare @type: VendorPaymentDataOnDemand: @Component;
    
    private Random VendorPaymentDataOnDemand.rnd = new SecureRandom();
    
    private List<VendorPayment> VendorPaymentDataOnDemand.data;
    
    public VendorPayment VendorPaymentDataOnDemand.getNewTransientVendorPayment(int index) {
        VendorPayment obj = new VendorPayment();
        setPayDate(obj, index);
        setPaymentAmount(obj, index);
        setTax(obj, index);
        setVendorInvoiceNo(obj, index);
        return obj;
    }
    
    public void VendorPaymentDataOnDemand.setPayDate(VendorPayment obj, int index) {
        Date payDate = new GregorianCalendar(Calendar.getInstance().get(Calendar.YEAR), Calendar.getInstance().get(Calendar.MONTH), Calendar.getInstance().get(Calendar.DAY_OF_MONTH), Calendar.getInstance().get(Calendar.HOUR_OF_DAY), Calendar.getInstance().get(Calendar.MINUTE), Calendar.getInstance().get(Calendar.SECOND) + new Double(Math.random() * 1000).intValue()).getTime();
        obj.setPayDate(payDate);
    }
    
    public void VendorPaymentDataOnDemand.setPaymentAmount(VendorPayment obj, int index) {
        Double paymentAmount = new Integer(index).doubleValue();
        obj.setPaymentAmount(paymentAmount);
    }
    
    public void VendorPaymentDataOnDemand.setTax(VendorPayment obj, int index) {
        Double tax = new Integer(index).doubleValue();
        obj.setTax(tax);
    }
    
    public void VendorPaymentDataOnDemand.setVendorInvoiceNo(VendorPayment obj, int index) {
        String vendorInvoiceNo = "vendorInvoiceNo_" + index;
        obj.setVendorInvoiceNo(vendorInvoiceNo);
    }
    
    public VendorPayment VendorPaymentDataOnDemand.getSpecificVendorPayment(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        VendorPayment obj = data.get(index);
        Long id = obj.getId();
        return VendorPayment.findVendorPayment(id);
    }
    
    public VendorPayment VendorPaymentDataOnDemand.getRandomVendorPayment() {
        init();
        VendorPayment obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return VendorPayment.findVendorPayment(id);
    }
    
    public boolean VendorPaymentDataOnDemand.modifyVendorPayment(VendorPayment obj) {
        return false;
    }
    
    public void VendorPaymentDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = VendorPayment.findVendorPaymentEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'VendorPayment' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<VendorPayment>();
        for (int i = 0; i < 10; i++) {
            VendorPayment obj = getNewTransientVendorPayment(i);
            try {
                obj.persist();
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
