// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.myshop.domain;

import com.myshop.domain.AddressType;

privileged aspect AddressType_Roo_JavaBean {
    
    public String AddressType.getAddressType() {
        return this.addressType;
    }
    
    public void AddressType.setAddressType(String addressType) {
        this.addressType = addressType;
    }
    
}
