// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.myshop.domain;

import com.myshop.domain.PaymentTerm;

privileged aspect PaymentTerm_Roo_JavaBean {
    
    public String PaymentTerm.getTerm() {
        return this.term;
    }
    
    public void PaymentTerm.setTerm(String term) {
        this.term = term;
    }
    
}
