// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.myshop.domain;

import com.myshop.domain.PaymentTerm;

privileged aspect PaymentTerm_Roo_JavaBean {
    
    public String PaymentTerm.getPaymentTerm() {
        return this.paymentTerm;
    }
    
    public void PaymentTerm.setPaymentTerm(String paymentTerm) {
        this.paymentTerm = paymentTerm;
    }
    
}
